# Generated by Django 5.2 on 2025-05-22 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_solicitada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_trabajador', to=settings.AUTH_USER_MODEL),
        ),
    ]
