# Generated by Django 5.1.2 on 2025-05-23 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_rename_fecha_solicitudes_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_solicitada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
