# Generated by Django 5.2 on 2025-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitudes_fecha_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
