# Generated by Django 5.2 on 2025-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_solicitudes_fecha_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
    ]
