# Generated by Django 5.2 on 2025-05-24 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitudes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_solicitada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
