# Generated by Django 5.2 on 2025-05-26 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitudes_fecha_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
