# Generated by Django 5.2 on 2025-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_cargar_uuid_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
