# Generated by Django 5.2 on 2025-05-26 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_alter_solicitudes_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 5, 26)),
            preserve_default=False,
        ),
    ]
