# Generated by Django 5.2 on 2025-05-26 01:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_alter_solicitudes_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
