# Generated by Django 5.2 on 2025-05-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_alter_solicitudes_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='direccion',
            field=models.CharField(max_length=550),
        ),
    ]
