# Generated by Django 5.2 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_solicitudes_lat_solicitudes_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
