# Generated by Django 5.2 on 2025-05-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_alter_solicitudes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_finalizo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
