# Generated by Django 5.2 on 2025-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
