# Generated by Django 5.2 on 2025-05-26 00:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
