# Generated by Django 5.2 on 2025-05-26 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_cargar_uuid_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
