# Generated by Django 5.1.2 on 2025-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
